joy_node:
  ros__parameters:
    device_id: 0 
    deadzone: 0.1
    autorepeat_rate: 10.0 


teleop_node:
  ros__parameters:
    axis_linear: 
      x: 1
      y: 0
    scale_linear: 
      x: 1.0
      y: 1.0
    scale_linear_turbo: 
      x: 2.0
      y: 2.0

    axis_angular: 
      yaw: 2
    scale_angular: 
      yaw: 0.5
    scale_angular_turbo: 
      yaw: 1.0

    require_enable_button: false
    enable_turbo_button: 10

